name: Rails Lint

on:
  workflow_call:
    inputs:
      ruby-version-file:
        description: 'Path to Ruby version file'
        required: false
        type: string
        default: '.ruby-version'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
         ruby-version-file: ${{ inputs.ruby-version-file }}
         bundler-cache: true

     - name: Lint code for consistent style
       run: bin/rubocop -f github